package source.task;

import org.apache.commons.io.FileUtils;
import org.apache.kafka.connect.data.Schema;
import source.connector.HexGraphSourceConnector;
import org.apache.kafka.connect.source.SourceRecord;
import org.apache.kafka.connect.source.SourceTask;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.imageio.ImageIO;
import java.io.*;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import static source.config.HexGraphSourceConnectorConfig.DIRECTORY_SOURCE;
import static source.config.HexGraphSourceConnectorConfig.TOPIC_NAME;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jack' at '8/01/18 3:30 PM' with Gradle 2.10
 *
 * @author jack, @date 8/01/18 3:30 PM
 */
public class HexGraphSourceTask extends SourceTask {
    public static final Logger LOG = LoggerFactory.getLogger(HexGraphSourceTask.class);

    private String topic;
    private String directorySourceName;

    @Override
    public String version() {
        return new HexGraphSourceConnector().version();
    }

    @Override
    public void start(Map<String, String> props) {
        LOG.info("Image source task starting.");

        topic = props.get(TOPIC_NAME);
        directorySourceName = props.get(DIRECTORY_SOURCE);
    }

    @Override
    public List<SourceRecord> poll() throws InterruptedException {
        File sourceDirectory = new File(directorySourceName);

        if (!sourceDirectory.isDirectory()) {
            throw new RuntimeException(sourceDirectory.getName() + " is not a directory.");
        }

        File[] sourceFiles = sourceDirectory.listFiles();

        List<SourceRecord> sourceRecords = new ArrayList<>();

        for (File sourceFile : sourceFiles) {
            try {
                LOG.info("File: " + sourceFile.getCanonicalPath());
                if (ImageIO.read(sourceFile) == null) {
                    LOG.info(sourceFile.getName() + " is not an image.");
                    sourceFile.delete();
                    continue;
                }

                File sinkDirectory = new File(sourceDirectory.getCanonicalPath() + "_sink");
                boolean hasFileMoved = moveFile(sourceFile, sinkDirectory);
                if (!hasFileMoved) {
                    throw new RuntimeException(sourceFile.getCanonicalPath() + "failed to move.");
                }

                sourceRecords.add(new SourceRecord(Collections.emptyMap(), Collections.emptyMap(), topic, Schema.STRING_SCHEMA, sinkDirectory.getCanonicalPath() + File.separator + sourceFile.getName()));
            } catch (IOException e) {
                LOG.error(e.getMessage());
            }
        }

        return sourceRecords;
    }

    private boolean moveFile(File sourceFile, File sinkDirectory) throws IOException {
        FileUtils.copyFileToDirectory(sourceFile, sinkDirectory, true);
        LOG.info("Copied source file " + sourceFile.getCanonicalPath() + " to " + sinkDirectory.getCanonicalPath() + File.separator + sourceFile.getName() + ".");

        if (new File(sinkDirectory.getCanonicalPath() + File.separator + sourceFile.getName()).exists()) {
            sourceFile.delete();
            LOG.info(sourceFile.getCanonicalPath() + " deleted.");
            return true;
        }
        return false;
    }

    @Override
    public void stop() {
        LOG.info("Image source task stopping.");
    }
}
