/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jack' at '8/01/18 3:30 PM' with Gradle 2.10
 *
 * @author jack, @date 8/01/18 3:30 PM
 */
public class FileStreamSourceTask extends SourceTask {
    public boolean someLibraryMethod() {
        return true;
    }
}
